### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by kikirizki** [Totoro97/f2-nerf#21]
Hi thank you for your great work, I got compilation error on ubuntu 22.04, it's work well on ubuntu 20.04
I got the following error, when running `cmake --build build --target main --config RelWithDebInfo -j`

`eigen error fatal error: Core: No such file or directory`

**Comment by Totoro97** [comment]
Hi, thanks for your interset in this project. Have you add the `--recursive` argument in cloning the project?

**Comment by kikirizki** [comment]
Thank you for your response, I somehow solved it by adding this flag

```shell
-DENABLE_PRECOMPILED_HEADERS=OFF
```
